# Workflow name that appears in the Actions tab
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#name
name: Playwright Tests

# Defines when the workflow will run
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# A workflow run is made up of one or more jobs
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobs
jobs:
  test:
    # Prevents jobs from running endlessly if they're stuck
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
    timeout-minutes: 60
    # The type of runner that the job will run on
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    steps:
    # Checks out your repository under $GITHUB_WORKSPACE
    # https://github.com/actions/checkout
    - uses: actions/checkout@v4
    
    # Sets up Node.js environment
    # https://github.com/actions/setup-node
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    # Install dependencies using clean install to ensure consistent builds
    # https://docs.npmjs.com/cli/v8/commands/npm-ci
    - name: Install dependencies
      run: npm ci
    
    # Install Playwright browsers and their dependencies
    # https://playwright.dev/docs/cli#install-system-dependencies
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    # Run Playwright tests
    # https://playwright.dev/docs/test-cli
    - name: Run Playwright tests
      run: npx playwright test
    
    # Upload test results on success or failure
    # https://github.com/actions/upload-artifact
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30 